LojaProdutos.Web.Mvc/Models/ErrorViewModel.cs
using System;

namespace LojaProdutos.Web.Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LojaProdutos.Web.Mvc/Controllers/HomeController.cs
using LojaProdutos.Web.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LojaProdutos.Web.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LojaProdutos.Web.Mvc/Controllers/LojaProdutosController.cs
using Microsoft.AspNetCore.Mvc;
using LojaProdutos.Application.Interfaces;
using LojaProdutos.Application.ViewModels;

namespace LojaProdutos.Web.Mvc.Controllers
{
    public class LojaProdutosController : Controller
    {
        private ILojaProdutoService _lojaProdutoService;

        public LojaProdutosController(ILojaProdutoService lojaProduto)
        {
            _lojaProdutoService = lojaProduto;
        }
        public IActionResult Index()
        {
            LojaProdutoViewModel model = _lojaProdutoService.GetProdutos();
            return View(model);
        }
    }
}

LojaProdutos.Web.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LojaProdutos.Web.Mvc/Views/LojaProdutos/Index.cshtml
@model LojaProdutos.Application.ViewModels.LojaProdutoViewModel

<table id="LojaProduto" class="table table-bordered table-hover">
    <thead>
        <tr class="">
            <th>IdProduto</th>
            <th>NomeProduto</th>
            <th>PrecoProduto</th>
            <th>QuantidadeProduto</th>
            <th>ProdutoAtivo</th>
            <th>DataCadastroProduto</th>
            <th>DataAtualizacaoProduto</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var produtos in Model.Produtos)
        {
            <tr style="height: 60px;">
                <td>@produtos.IdProduto</td>
                <td>@produtos.NomeProduto</td>
                <td>@produtos.PrecoProduto</td>
                <td>@produtos.QuantidadeProduto</td>
                <td>@produtos.ProdutoAtivo</td>
                <td>@produtos.DataCadastroProduto</td>
                <td>@produtos.DataAtualizacaoProduto</td>
            </tr>
        }
    </tbody>
</table>

LojaProdutos.Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LojaProdutos.Web.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LojaProdutos.Web.Mvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LojaProdutos" asp-action="Index">Visualizar Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LojaProdutos.Web.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>